### PR TITLE
Support CloudAPI's Ping endpoint

### PR DESCRIPTION
**Pull request by cheapRoc**
This commit is part 2 of 2 for my push to introduce unit testing. It made sense to create the HTTP mock along with the new Ping endpoint functionality since it was a basic feature. The HTTP mock and setup in this PR will work across all other endpoints with minimal effort.

This PR is missing `authentication.NewTestSigner()` which is coming in a subsequent PR after this.

### CODE REVIEW

**Comment by cheapRoc** [comment]
@stack72 Once #52 goes in I can rebase this branch and we can test the entire set of changes all at once using this PR.

**Comment by stack72** [comment]
Tests pass as expected :)

```
triton-go [cheapRoc-ping-alone] % make
go vet .
==> Checking for unchecked errors
==> Running unit tests
go test -v -timeout=30s -parallel=1 github.com/joyent/triton-go github.com/joyent/triton-go/account github.com/joyent/triton-go/authentication github.com/joyent/triton-go/client github.com/joyent/triton-go/compute github.com/joyent/triton-go/identity github.com/joyent/triton-go/network github.com/joyent/triton-go/storage
?   	github.com/joyent/triton-go	[no test files]
PASS
ok  	github.com/joyent/triton-go/account	0.014s
?   	github.com/joyent/triton-go/authentication	[no test files]
=== RUN   TestNew
=== RUN   TestNew/default
=== RUN   TestNew/missing_url
=== RUN   TestNew/bad_tritonURL
=== RUN   TestNew/bad_mantaURL
=== RUN   TestNew/missing_accountName
=== RUN   TestNew/missing_signer
=== RUN   TestNew/default_SSH_agent_auth
--- PASS: TestNew (0.00s)
    --- PASS: TestNew/default (0.00s)
    --- PASS: TestNew/missing_url (0.00s)
    --- PASS: TestNew/bad_tritonURL (0.00s)
    --- PASS: TestNew/bad_mantaURL (0.00s)
    --- PASS: TestNew/missing_accountName (0.00s)
    --- PASS: TestNew/missing_signer (0.00s)
    --- PASS: TestNew/default_SSH_agent_auth (0.00s)
PASS
ok  	github.com/joyent/triton-go/client	0.010s
=== RUN   TestPing
=== RUN   TestPing/successful
=== RUN   TestPing/EOF_decode
=== RUN   TestPing/error
=== RUN   TestPing/404
=== RUN   TestPing/410
=== RUN   TestPing/bad_decode
--- PASS: TestPing (0.00s)
    --- PASS: TestPing/successful (0.00s)
    --- PASS: TestPing/EOF_decode (0.00s)
    --- PASS: TestPing/error (0.00s)
    --- PASS: TestPing/404 (0.00s)
    --- PASS: TestPing/410 (0.00s)
    --- PASS: TestPing/bad_decode (0.00s)
PASS
ok  	github.com/joyent/triton-go/compute	0.011s
?   	github.com/joyent/triton-go/identity	[no test files]
PASS
ok  	github.com/joyent/triton-go/network	0.016s
?   	github.com/joyent/triton-go/storage	[no test files]
```

**Comment by cheapRoc** [comment]
Cool this was rebased as well.

**Comment by stack72** [comment]
LGTM! Let's merge it in :) 

Remember to add a new section to the changelog for the change of functionality ;)

**Pull request merged**
